/* Generated by AN DISI Unibo */ 
package it.unibo.waiterengine

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waiterengine ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
					var StepTime = 445L
					val BackTime     = 2 * StepTime / 3
					
					val mapRoom  = "teaRoomExplored"
					var XPoint = "0"
					var YPoint = "0"
					
					val TableClearTime = 4000L
					val TableSanitizeTime = 2000L
					val TableCleanTime = 2000L
					
					var CmdToPerform = ""  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("waiterengine || START")
						updateResourceRep( "startState"  
						)
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.plannerUtil.loadRoomMap( mapRoom  )
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
						forward("engineReady", "engineReady(P)" ,"waitermind" ) 
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						println("waiterengine || waitCmd")
						updateResourceRep( "waitCmd"  
						)
					}
					 transition(edgeName="t023",targetState="planPath",cond=whenRequest("moveTo"))
					transition(edgeName="t024",targetState="cleanTable",cond=whenDispatch("clean"))
				}	 
				state("planPath") { //this:State
					action { //it:State
						println("waiterengine || planPath")
						updateResourceRep( "planPath"  
						)
						if( checkMsgContent( Term.createTerm("moveTo(X,Y)"), Term.createTerm("moveTo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 XPoint = payloadArg(0)
											   YPoint = payloadArg(1)			  
						}
						println("moveTo ($XPoint,$YPoint)")
						itunibo.planner.plannerUtil.planForGoal( "$XPoint", "$YPoint"  )
					}
					 transition( edgeName="goto",targetState="readStep", cond=doswitch() )
				}	 
				state("readStep") { //this:State
					action { //it:State
						  CmdToPerform = itunibo.planner.plannerUtil.getNextPlannedMove()  
					}
					 transition( edgeName="goto",targetState="execStep", cond=doswitchGuarded({ CmdToPerform == "w" 
					}) )
					transition( edgeName="goto",targetState="execMove", cond=doswitchGuarded({! ( CmdToPerform == "w" 
					) }) )
				}	 
				state("execMove") { //this:State
					action { //it:State
						forward("cmd", "cmd($CmdToPerform)" ,"basicrobot" ) 
						delay(200) 
					}
					 transition( edgeName="goto",targetState="updateMap", cond=doswitch() )
				}	 
				state("endPath") { //this:State
					action { //it:State
						println("waiterengine || endPath")
						updateResourceRep( "endPath"  
						)
						println("done moveTo($XPoint,$YPoint)")
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
						answer("moveTo", "done", "done($XPoint,$YPoint)"   )  
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("execStep") { //this:State
					action { //it:State
						request("step", "step($StepTime)" ,"basicrobot" )  
					}
					 transition(edgeName="t125",targetState="updateMap",cond=whenReply("stepdone"))
					transition(edgeName="t126",targetState="errorHandler",cond=whenReply("stepfail"))
				}	 
				state("updateMap") { //this:State
					action { //it:State
						updateResourceRep( itunibo.planner.plannerUtil.getMapOneLine()  
						)
						itunibo.planner.plannerUtil.updateMap( "$CmdToPerform"  )
					}
					 transition( edgeName="goto",targetState="readStep", cond=doswitchGuarded({ CmdToPerform.length > 0  
					}) )
					transition( edgeName="goto",targetState="endPath", cond=doswitchGuarded({! ( CmdToPerform.length > 0  
					) }) )
				}	 
				state("errorHandler") { //this:State
					action { //it:State
						println("waiterengine | errorHandler")
						if( checkMsgContent( Term.createTerm("stepfail(DURATION,CAUSE)"), Term.createTerm("stepfail(DURATION,CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val D = payloadArg(0).toLong()  ; val Dt = Math.abs(StepTime-D); val BackT = D/2  
								println("robotmapper stepFail D= $D, BackTime = ${BackTime} BackT=$BackT")
								if(  D > BackTime  
								 ){forward("cmd", "cmd(s)" ,"basicrobot" ) 
								delay(BackT)
								forward("cmd", "cmd(h)" ,"basicrobot" ) 
								}
								itunibo.planner.plannerUtil.updateMapObstacleOnCurrentDirection(  )
								itunibo.planner.plannerUtil.showCurrentRobotState(  )
								updateResourceRep( "stepFail"  
								)
								delay(500) 
						}
					}
					 transition( edgeName="goto",targetState="readStep", cond=doswitchGuarded({ CmdToPerform.length > 0  
					}) )
					transition( edgeName="goto",targetState="endPath", cond=doswitchGuarded({! ( CmdToPerform.length > 0  
					) }) )
				}	 
				state("cleanTable") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("clean(R)"), Term.createTerm("clean(R)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0) == "1"  
								 ){println("waiterengine 	|| clearing")
								delay(TableClearTime)
								}
								if(  payloadArg(0) == "2"  
								 ){println("waiterengine 	|| sanitizing")
								delay(TableSanitizeTime)
								}
								if(  payloadArg(0) == "3"  
								 ){println("waiterengine 	|| cleaning")
								delay(TableCleanTime)
								}
						}
						forward("doneCleanRun", "doneCleanRun(P)" ,"waitermind" ) 
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
